<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'writecrow\\CountryCodeConverter\\' => array($vendorDir . '/writecrow/country_code_converter/src', $vendorDir . '/writecrow/country_code_converter/test'),
    'Mihdan\\IndexNow\\' => array($baseDir . '/src'),
);
